name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.4.9
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Build and test with Rake
      run: |
        cd
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        exec $SHELL

        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
        exec $SHELL

        rbenv install 2.4.9
        rbenv global 2.4.9
        ruby -v
        gem install bundler
        bundle install --path=vendor/bundle
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rate test
