name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.4.9
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --path=vendor/bundle
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rate test
